# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET {{host}}
<>
###
GET {{host}}/api/coupons
###
GET {{host}}/api/products/p0001
Content-Type: application/json
###
GET {{host}}/api/products
Content-Type: application/json
###
GET {{host}}/api/orders
Content-Type: application/json
###
GET {{host}}/docs
Content-Type: text/html
###
GET {{host}}/login
Content-Type: text/html
###
POST {{host}}/login
Content-Type: application/json

###